"""Add youtube_link to Tutorial

Revision ID: 0ffc5f828a90
Revises: 10dd985f0f08
Create Date: 2025-06-23 10:09:07.630331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffc5f828a90'
down_revision = '10dd985f0f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=300), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
